work at genconf

diff --git a/mini-gcc b/mini-gcc
--- a/mini-gcc
+++ b/mini-gcc
@@ -24,9 +24,11 @@ echo_verbose minilibdir: $MLIBDIR
 
 COMMONCFLAGS="-I. -fno-stack-protector -fdata-sections -fomit-frame-pointer -ffunction-sections \
 		-Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-const-variable -Wall \
-		-nodefaultlibs -static -nostdlib -DMLIB -fno-builtin -nostdinc\
+		-nodefaultlibs -static -nostdlib -DMLIB -fno-builtin\
 		-I$MLIBDIR/compat -I$MLIBDIR/headers/common-links -I$MLIBDIR/headers/common -I$MLIBDIR/headers/linux_x64 -I$MLIBDIR -I./ \
 		-I$MLIBDIR/include -Os"
+		
+		#-nodefaultlibs -static -nostdlib -DMLIB -fno-builtin -nostdinc\
 
 # needs os detection. but not important for now
 CFLAGS="$COMMONCFLAGS -DLINUX -DX64"
@@ -80,6 +82,9 @@ before options and parameters for gcc.
 					onlytext     ( drop all sections beside the text segment )
 					text_and_bss ( keep also the bss segment )
 
+--autoconf / -ac
+				This is going to generate 
+
 --genconf 'outfile' 'infile1' 'infile2' ...:
 				parses the sourcefiles 'infile1',.. and writes a config into
 				outfile, which enables compiling of all used minilib functions
@@ -129,6 +134,22 @@ checkconfig (){
 }
 
 
+genconfig(){
+						echo '# config generated by mini-gcc.
+# Save default. The minibuf is needed for malloc, printf, and file streams. 
+mini_buf 1024
+
+# define headerguards, to prevent parsing the standard header
+HEADERGUARDS
+
+'
+
+		echo "$headerguards_h" "$genconfigmacros_h" | ($REAL_CC $CFLAGS -Dincluded_minilib_h -E $@ -include <( cat - ) ) \
+				| sed -n 's/^.*_M_MLIB_\(.*\)_M_.*/mini_\1/p' | sort -u
+				return $?
+}
+
+
 ARGS=$@
 
 if [ "$1" = "" ]
@@ -139,6 +160,7 @@ fi
 
 opt=1
 opt_force=0
+opt_autoconf=0
 
 while [ "$1" != "" ] && [ $opt = 1 ]
 do
@@ -156,12 +178,17 @@ do
 						opt_force=1
 						opt=1
 						;;
+				--autoconf )
+						shift
+						opt_autoconf=1
+						opt=1
+						;;
 				--genconf )
 						shift
 						outfile=$1
 						if [ -e $outfile ]
 						then
-								if [ $opt_force = 1 ]
+								if [ $opt_force == 1 ]
 								then
 										echo "Overwriting $outfile"
 								else
@@ -171,8 +198,7 @@ do
 						fi
 						echo generating config in $outfile
 						shift
-						echo "$headerguards_h" "$genconfigmacros_h" | ($REAL_CC $CFLAGS -Dincluded_minilib_h -E $@ -include <( cat - ) ) \
-								| sed -n 's/^.*_M_MLIB_\(.*\)_M_.*/mini_\1/p' | sort -u > $outfile
+						genconfig $@ > $outfile
 						exit $?
 						;;
 				--ldscript )
@@ -214,9 +240,15 @@ if [ "$1" == "" ]; then
 fi
 
 #echo args: $@
+if [ $opt_autoconf == 1 ]
+then
+		exec_gcc $@
+else
+		exec_gcc $@
+fi
 
-exec_gcc $@
 ret=$?
+
 if [ $ret != 0 ]; then
 		echo Error.
 		echo Failed command:
@@ -281,173 +313,83 @@ INCLUDESRC(){
 # when make header ist invoked
 
 # --- define_functions-start: generate --- #
-mini_fileno(){ 
-  echo "#define mini_fileno generate" 
-}
-mini_strncmp(){ 
-  echo "#define mini_strncmp generate" 
-}
-mini_itodec(){ 
-  echo "#define mini_itodec generate" 
-}
-mini_print(){ 
-  echo "#define mini_print generate" 
-}
-mini_tcsetattr(){ 
-  echo "#define mini_tcsetattr generate" 
-}
-mini_fsetpos(){ 
-  echo "#define mini_fsetpos generate" 
-}
-mini_fprintf(){ 
-  echo "#define mini_fprintf generate" 
-}
-mini_mprotect(){ 
-  echo "#define mini_mprotect generate" 
-}
-mini_printf(){ 
-  echo "#define mini_printf generate" 
-}
-mini_snprintf(){ 
-  echo "#define mini_snprintf generate" 
-}
-mini_strerror(){ 
-  echo "#define mini_strerror generate" 
-}
-mini_fgetpos(){ 
-  echo "#define mini_fgetpos generate" 
-}
-mini_fsync(){ 
-  echo "#define mini_fsync generate" 
-}
-mini_ftruncate(){ 
-  echo "#define mini_ftruncate generate" 
-}
-mini_strcmp(){ 
-  echo "#define mini_strcmp generate" 
-}
-mini_fread(){ 
-  echo "#define mini_fread generate" 
-}
-mini__itobin(){ 
-  echo "#define mini__itobin generate" 
-}
-mini_printl(){ 
-  echo "#define mini_printl generate" 
-}
-mini_dup(){ 
-  echo "#define mini_dup generate" 
-}
-mini_strcat(){ 
-  echo "#define mini_strcat generate" 
-}
-mini_uitodec(){ 
-  echo "#define mini_uitodec generate" 
-}
-mini_vsnprintf(){ 
-  echo "#define mini_vsnprintf generate" 
-}
-mini_close(){ 
-  echo "#define mini_close generate" 
-}
-mini_lseek(){ 
-  echo "#define mini_lseek generate" 
-}
-mini_isspace(){ 
-  echo "#define mini_isspace generate" 
-}
-mini_fstat(){ 
-  echo "#define mini_fstat generate" 
-}
-mini_putchar(){ 
-  echo "#define mini_putchar generate" 
-}
-mini_dprintf(){ 
-  echo "#define mini_dprintf generate" 
-}
-mini_memcpy(){ 
-  echo "#define mini_memcpy generate" 
-}
-mini_fseek(){ 
-  echo "#define mini_fseek generate" 
-}
-mini_fwrite(){ 
-  echo "#define mini_fwrite generate" 
-}
-mini_strncpy(){ 
-  echo "#define mini_strncpy generate" 
+mini_rename(){ 
+  echo "#define mini_rename generate" 
 }
 mini_getpid(){ 
   echo "#define mini_getpid generate" 
 }
-mini_time(){ 
-  echo "#define mini_time generate" 
+mini_fopen(){ 
+  echo "#define mini_fopen generate" 
 }
-mini_memfrob(){ 
-  echo "#define mini_memfrob generate" 
+mini_printl(){ 
+  echo "#define mini_printl generate" 
 }
-mini_dup3(){ 
-  echo "#define mini_dup3 generate" 
+mini__itobin(){ 
+  echo "#define mini__itobin generate" 
 }
-mini_dup2(){ 
-  echo "#define mini_dup2 generate" 
+mini_snprintf(){ 
+  echo "#define mini_snprintf generate" 
 }
-mini_rename(){ 
-  echo "#define mini_rename generate" 
+mini_itoHEX(){ 
+  echo "#define mini_itoHEX generate" 
+}
+mini_getcwd(){ 
+  echo "#define mini_getcwd generate" 
+}
+mini_fwrite(){ 
+  echo "#define mini_fwrite generate" 
+}
+mini_itohex(){ 
+  echo "#define mini_itohex generate" 
+}
+mini_fsetpos(){ 
+  echo "#define mini_fsetpos generate" 
+}
+mini_uitodec(){ 
+  echo "#define mini_uitodec generate" 
+}
+mini_strlen(){ 
+  echo "#define mini_strlen generate" 
 }
 mini_sprintf(){ 
   echo "#define mini_sprintf generate" 
 }
-mini_memset(){ 
-  echo "#define mini_memset generate" 
+mini_atoi(){ 
+  echo "#define mini_atoi generate" 
 }
-mini_read(){ 
-  echo "#define mini_read generate" 
+mini_lseek(){ 
+  echo "#define mini_lseek generate" 
 }
-mini_ioctl(){ 
-  echo "#define mini_ioctl generate" 
+mini_isprint(){ 
+  echo "#define mini_isprint generate" 
 }
-mini_free(){ 
-  echo "#define mini_free generate" 
-}
-mini_memcmp(){ 
-  echo "#define mini_memcmp generate" 
-}
-mini_fputs(){ 
-  echo "#define mini_fputs generate" 
-}
-mini_creat(){ 
-  echo "#define mini_creat generate" 
-}
-mini_fopen(){ 
-  echo "#define mini_fopen generate" 
-}
-mini_fclose(){ 
-  echo "#define mini_fclose generate" 
-}
-mini__itohex(){ 
-  echo "#define mini__itohex generate" 
-}
-mini_write(){ 
-  echo "#define mini_write generate" 
+mini_ftruncate(){ 
+  echo "#define mini_ftruncate generate" 
 }
 mini_open(){ 
   echo "#define mini_open generate" 
 }
-mini_rand(){ 
-  echo "#define mini_rand generate" 
+mini_tcsetattr(){ 
+  echo "#define mini_tcsetattr generate" 
 }
 mini_srand(){ 
   echo "#define mini_srand generate" 
 }
+mini_fprintf(){ 
+  echo "#define mini_fprintf generate" 
+}
 mini_tcgetattr(){ 
   echo "#define mini_tcgetattr generate" 
 }
-mini_dtodec(){ 
-  echo "#define mini_dtodec generate" 
+mini_rand(){ 
+  echo "#define mini_rand generate" 
 }
-mini_unlink(){ 
-  echo "#define mini_unlink generate" 
+mini_fputs(){ 
+  echo "#define mini_fputs generate" 
+}
+mini_strcpy(){ 
+  echo "#define mini_strcpy generate" 
 }
 mini_def(){ 
   echo "#define mini_def generate" 
@@ -455,53 +397,143 @@ mini_def(){
 mini_malloc(){ 
   echo "#define mini_malloc generate" 
 }
-mini_stat(){ 
-  echo "#define mini_stat generate" 
-}
-mini_getcwd(){ 
-  echo "#define mini_getcwd generate" 
-}
-mini_ftell(){ 
-  echo "#define mini_ftell generate" 
-}
-mini_feof(){ 
-  echo "#define mini_feof generate" 
-}
-mini_rewind(){ 
-  echo "#define mini_rewind generate" 
-}
-mini_isprint(){ 
-  echo "#define mini_isprint generate" 
-}
-mini_strlen(){ 
-  echo "#define mini_strlen generate" 
-}
-mini_strcpy(){ 
-  echo "#define mini_strcpy generate" 
-}
-mini_fputc(){ 
-  echo "#define mini_fputc generate" 
-}
-mini_itohex(){ 
-  echo "#define mini_itohex generate" 
-}
-mini_gettimeofday(){ 
-  echo "#define mini_gettimeofday generate" 
+mini_strerror(){ 
+  echo "#define mini_strerror generate" 
 }
 mini_puts(){ 
   echo "#define mini_puts generate" 
 }
-mini_itoHEX(){ 
-  echo "#define mini_itoHEX generate" 
+mini_putchar(){ 
+  echo "#define mini_putchar generate" 
 }
-mini_atoi(){ 
-  echo "#define mini_atoi generate" 
+mini_strcmp(){ 
+  echo "#define mini_strcmp generate" 
+}
+mini_fileno(){ 
+  echo "#define mini_fileno generate" 
+}
+mini_creat(){ 
+  echo "#define mini_creat generate" 
+}
+mini_select(){ 
+  echo "#define mini_select generate" 
+}
+mini_itodec(){ 
+  echo "#define mini_itodec generate" 
+}
+mini_fseek(){ 
+  echo "#define mini_fseek generate" 
+}
+mini_isspace(){ 
+  echo "#define mini_isspace generate" 
+}
+mini_fstat(){ 
+  echo "#define mini_fstat generate" 
+}
+mini_printf(){ 
+  echo "#define mini_printf generate" 
+}
+mini_memcmp(){ 
+  echo "#define mini_memcmp generate" 
+}
+mini_vsnprintf(){ 
+  echo "#define mini_vsnprintf generate" 
+}
+mini_rewind(){ 
+  echo "#define mini_rewind generate" 
+}
+mini_fread(){ 
+  echo "#define mini_fread generate" 
+}
+mini_dprintf(){ 
+  echo "#define mini_dprintf generate" 
+}
+mini_ftell(){ 
+  echo "#define mini_ftell generate" 
+}
+mini_fsync(){ 
+  echo "#define mini_fsync generate" 
+}
+mini_memset(){ 
+  echo "#define mini_memset generate" 
+}
+mini_free(){ 
+  echo "#define mini_free generate" 
+}
+mini__itohex(){ 
+  echo "#define mini__itohex generate" 
+}
+mini_memcpy(){ 
+  echo "#define mini_memcpy generate" 
+}
+mini_unlink(){ 
+  echo "#define mini_unlink generate" 
+}
+mini_ioctl(){ 
+  echo "#define mini_ioctl generate" 
+}
+mini_mprotect(){ 
+  echo "#define mini_mprotect generate" 
+}
+mini_dup(){ 
+  echo "#define mini_dup generate" 
 }
 mini_getenv(){ 
   echo "#define mini_getenv generate" 
 }
-mini_select(){ 
-  echo "#define mini_select generate" 
+mini_close(){ 
+  echo "#define mini_close generate" 
+}
+mini_fputc(){ 
+  echo "#define mini_fputc generate" 
+}
+mini_strncpy(){ 
+  echo "#define mini_strncpy generate" 
+}
+mini_print(){ 
+  echo "#define mini_print generate" 
+}
+mini_strcat(){ 
+  echo "#define mini_strcat generate" 
+}
+mini_memfrob(){ 
+  echo "#define mini_memfrob generate" 
+}
+mini_strncmp(){ 
+  echo "#define mini_strncmp generate" 
+}
+mini_read(){ 
+  echo "#define mini_read generate" 
+}
+mini_feof(){ 
+  echo "#define mini_feof generate" 
+}
+mini_gettimeofday(){ 
+  echo "#define mini_gettimeofday generate" 
+}
+mini_time(){ 
+  echo "#define mini_time generate" 
+}
+mini_write(){ 
+  echo "#define mini_write generate" 
+}
+mini_fclose(){ 
+  echo "#define mini_fclose generate" 
+}
+mini_fgetpos(){ 
+  echo "#define mini_fgetpos generate" 
+}
+mini_dup2(){ 
+  echo "#define mini_dup2 generate" 
+}
+mini_stat(){ 
+  echo "#define mini_stat generate" 
+}
+mini_dtodec(){ 
+  echo "#define mini_dtodec generate" 
+}
+mini_dup3(){ 
+  echo "#define mini_dup3 generate" 
 }
 # --- define_functions-end: generate --- #
 
@@ -745,80 +777,80 @@ genconfigmacros_h='
 // when make header ist invoked
 
 // --- define_macros-start: generate --- //
-#define fileno(...) _M_MLIB_fileno_M_()
-#define strncmp(...) _M_MLIB_strncmp_M_()
-#define itodec(...) _M_MLIB_itodec_M_()
-#define print(...) _M_MLIB_print_M_()
-#define tcsetattr(...) _M_MLIB_tcsetattr_M_()
-#define fsetpos(...) _M_MLIB_fsetpos_M_()
-#define fprintf(...) _M_MLIB_fprintf_M_()
-#define mprotect(...) _M_MLIB_mprotect_M_()
-#define printf(...) _M_MLIB_printf_M_()
-#define snprintf(...) _M_MLIB_snprintf_M_()
-#define strerror(...) _M_MLIB_strerror_M_()
-#define fgetpos(...) _M_MLIB_fgetpos_M_()
-#define fsync(...) _M_MLIB_fsync_M_()
-#define ftruncate(...) _M_MLIB_ftruncate_M_()
-#define strcmp(...) _M_MLIB_strcmp_M_()
-#define fread(...) _M_MLIB_fread_M_()
-#define _itobin(...) _M_MLIB__itobin_M_()
-#define printl(...) _M_MLIB_printl_M_()
-#define dup(...) _M_MLIB_dup_M_()
-#define strcat(...) _M_MLIB_strcat_M_()
-#define uitodec(...) _M_MLIB_uitodec_M_()
-#define vsnprintf(...) _M_MLIB_vsnprintf_M_()
-#define close(...) _M_MLIB_close_M_()
-#define lseek(...) _M_MLIB_lseek_M_()
-#define isspace(...) _M_MLIB_isspace_M_()
-#define fstat(...) _M_MLIB_fstat_M_()
-#define putchar(...) _M_MLIB_putchar_M_()
-#define dprintf(...) _M_MLIB_dprintf_M_()
-#define memcpy(...) _M_MLIB_memcpy_M_()
-#define fseek(...) _M_MLIB_fseek_M_()
-#define fwrite(...) _M_MLIB_fwrite_M_()
-#define strncpy(...) _M_MLIB_strncpy_M_()
-#define getpid(...) _M_MLIB_getpid_M_()
-#define time(...) _M_MLIB_time_M_()
-#define memfrob(...) _M_MLIB_memfrob_M_()
-#define dup3(...) _M_MLIB_dup3_M_()
-#define dup2(...) _M_MLIB_dup2_M_()
 #define rename(...) _M_MLIB_rename_M_()
-#define sprintf(...) _M_MLIB_sprintf_M_()
-#define memset(...) _M_MLIB_memset_M_()
-#define read(...) _M_MLIB_read_M_()
-#define ioctl(...) _M_MLIB_ioctl_M_()
-#define free(...) _M_MLIB_free_M_()
-#define memcmp(...) _M_MLIB_memcmp_M_()
-#define fputs(...) _M_MLIB_fputs_M_()
-#define creat(...) _M_MLIB_creat_M_()
+#define getpid(...) _M_MLIB_getpid_M_()
 #define fopen(...) _M_MLIB_fopen_M_()
-#define fclose(...) _M_MLIB_fclose_M_()
-#define _itohex(...) _M_MLIB__itohex_M_()
-#define write(...) _M_MLIB_write_M_()
+#define printl(...) _M_MLIB_printl_M_()
+#define _itobin(...) _M_MLIB__itobin_M_()
+#define snprintf(...) _M_MLIB_snprintf_M_()
+#define itoHEX(...) _M_MLIB_itoHEX_M_()
+#define getcwd(...) _M_MLIB_getcwd_M_()
+#define fwrite(...) _M_MLIB_fwrite_M_()
+#define itohex(...) _M_MLIB_itohex_M_()
+#define fsetpos(...) _M_MLIB_fsetpos_M_()
+#define uitodec(...) _M_MLIB_uitodec_M_()
+#define strlen(...) _M_MLIB_strlen_M_()
+#define sprintf(...) _M_MLIB_sprintf_M_()
+#define atoi(...) _M_MLIB_atoi_M_()
+#define lseek(...) _M_MLIB_lseek_M_()
+#define isprint(...) _M_MLIB_isprint_M_()
+#define ftruncate(...) _M_MLIB_ftruncate_M_()
 #define open(...) _M_MLIB_open_M_()
-#define rand(...) _M_MLIB_rand_M_()
+#define tcsetattr(...) _M_MLIB_tcsetattr_M_()
 #define srand(...) _M_MLIB_srand_M_()
+#define fprintf(...) _M_MLIB_fprintf_M_()
 #define tcgetattr(...) _M_MLIB_tcgetattr_M_()
-#define dtodec(...) _M_MLIB_dtodec_M_()
-#define unlink(...) _M_MLIB_unlink_M_()
+#define rand(...) _M_MLIB_rand_M_()
+#define fputs(...) _M_MLIB_fputs_M_()
+#define strcpy(...) _M_MLIB_strcpy_M_()
 #define def(...) _M_MLIB_def_M_()
 #define malloc(...) _M_MLIB_malloc_M_()
-#define stat(...) _M_MLIB_stat_M_()
-#define getcwd(...) _M_MLIB_getcwd_M_()
-#define ftell(...) _M_MLIB_ftell_M_()
-#define feof(...) _M_MLIB_feof_M_()
-#define rewind(...) _M_MLIB_rewind_M_()
-#define isprint(...) _M_MLIB_isprint_M_()
-#define strlen(...) _M_MLIB_strlen_M_()
-#define strcpy(...) _M_MLIB_strcpy_M_()
-#define fputc(...) _M_MLIB_fputc_M_()
-#define itohex(...) _M_MLIB_itohex_M_()
-#define gettimeofday(...) _M_MLIB_gettimeofday_M_()
+#define strerror(...) _M_MLIB_strerror_M_()
 #define puts(...) _M_MLIB_puts_M_()
-#define itoHEX(...) _M_MLIB_itoHEX_M_()
-#define atoi(...) _M_MLIB_atoi_M_()
-#define getenv(...) _M_MLIB_getenv_M_()
+#define putchar(...) _M_MLIB_putchar_M_()
+#define strcmp(...) _M_MLIB_strcmp_M_()
+#define fileno(...) _M_MLIB_fileno_M_()
+#define creat(...) _M_MLIB_creat_M_()
 #define select(...) _M_MLIB_select_M_()
+#define itodec(...) _M_MLIB_itodec_M_()
+#define fseek(...) _M_MLIB_fseek_M_()
+#define isspace(...) _M_MLIB_isspace_M_()
+#define fstat(...) _M_MLIB_fstat_M_()
+#define printf(...) _M_MLIB_printf_M_()
+#define memcmp(...) _M_MLIB_memcmp_M_()
+#define vsnprintf(...) _M_MLIB_vsnprintf_M_()
+#define rewind(...) _M_MLIB_rewind_M_()
+#define fread(...) _M_MLIB_fread_M_()
+#define dprintf(...) _M_MLIB_dprintf_M_()
+#define ftell(...) _M_MLIB_ftell_M_()
+#define fsync(...) _M_MLIB_fsync_M_()
+#define memset(...) _M_MLIB_memset_M_()
+#define free(...) _M_MLIB_free_M_()
+#define _itohex(...) _M_MLIB__itohex_M_()
+#define memcpy(...) _M_MLIB_memcpy_M_()
+#define unlink(...) _M_MLIB_unlink_M_()
+#define ioctl(...) _M_MLIB_ioctl_M_()
+#define mprotect(...) _M_MLIB_mprotect_M_()
+#define dup(...) _M_MLIB_dup_M_()
+#define getenv(...) _M_MLIB_getenv_M_()
+#define close(...) _M_MLIB_close_M_()
+#define fputc(...) _M_MLIB_fputc_M_()
+#define strncpy(...) _M_MLIB_strncpy_M_()
+#define print(...) _M_MLIB_print_M_()
+#define strcat(...) _M_MLIB_strcat_M_()
+#define memfrob(...) _M_MLIB_memfrob_M_()
+#define strncmp(...) _M_MLIB_strncmp_M_()
+#define read(...) _M_MLIB_read_M_()
+#define feof(...) _M_MLIB_feof_M_()
+#define gettimeofday(...) _M_MLIB_gettimeofday_M_()
+#define time(...) _M_MLIB_time_M_()
+#define write(...) _M_MLIB_write_M_()
+#define fclose(...) _M_MLIB_fclose_M_()
+#define fgetpos(...) _M_MLIB_fgetpos_M_()
+#define dup2(...) _M_MLIB_dup2_M_()
+#define stat(...) _M_MLIB_stat_M_()
+#define dtodec(...) _M_MLIB_dtodec_M_()
+#define dup3(...) _M_MLIB_dup3_M_()
 // --- define_macros-end: generate --- //
 // --- content-genconf-macros-end: TMPL ---
 '
