renaming. Stripped trailing "m"

diff --git a/mini-gcc b/mini-gcc
--- a/mini-gcc
+++ b/mini-gcc
@@ -153,17 +153,27 @@ checkconfig (){
 
 
 genconfig(){
-						echo '# config generated by mini-gcc.
-# Save default. The minibuf is needed for malloc, printf, and file streams. 
-mini_buf 1024
+						echo '# config generated by mini-gcc.'
+						if [ "$opt_nombuf" = "" ]; then
+								echo '# Save default. The minibuf is needed for malloc, printf, and file streams.
+mini_buf 1024'
+						else 
+								echo  '# Disabled mbuf. The minibuf is needed for malloc, printf, and file streams.
+# mini_buf 1024'
+						fi
 
+					echo '
 # define headerguards, to prevent parsing the standard header
 HEADERGUARDS
 
+# Startup function
+mini_start
+
+# function switches. Only functions named below will be compiled
 '
 
 		echo "$headerguards_h" "$genconfigmacros_h" | ($REAL_CC $CFLAGS -Dincluded_minilib_h -E $@ -include <( cat - ) ) \
-				| sed -n 's/^.*_M_MLIB_\(.*\)_M_.*/mini_\1/p' | sort -u
+				| sed 's/_M_MLIB_/\n_M_MLIB_/g' | sed -n 's/^.*_M_MLIB_\(.*\)_M_.*/mini_\1/p' | sort -u &2>/dev/null
 				return $?
 }
 
@@ -185,7 +195,12 @@ do
 		opt=0
 		case $1 in
 				--dump-minilib )
-						sed '0,/^#MINILIBGZ#$/d' $0 | gunzip -c
+						if [ -e $MLIBDIR/minilib.h ]
+						then 
+								cat $MLIBDIR/minilib.h
+						else
+								sed '0,/^#MINILIBGZ#$/d' $0 | gunzip -c
+						fi
 						exit 0
 						;;
 				--dump )
@@ -209,10 +224,27 @@ do
 						opt_force=1
 						opt=1
 						;;
+				--no-mbuf )
+						opt_nombuf="--no-mbuf"
+						shift
+						opt=1
+						;;
 				--autoconf | -ac )
 						shift
 						opt_autoconf=1
 						opt=1
+						#echo "Invoking: $0 --config <($0 --dump-conf $@) $@ --include <($0 --dump-minilib)" 
+						genconfig $@ 
+						echo Ok
+						source <( genconfig $@ ) > minilib.mconf.h
+						echo '#include "minilib.h"' >> minilib.mconf.h
+						$0 $@ -include minilib.mconf.h -include <($0 --dump-minilib) -DINCLUDESRC
+						exit $?
+						;;
+				--dump-conf )
+						shift
+						genconfig $@
+						exit $?
 						;;
 				--genconf )
 						shift
@@ -353,227 +385,230 @@ HEADERGUARDS(){
 # when make header ist invoked
 
 # --- define_functions-start: generate --- #
-mini_memfrob(){ 
-  echo "#define mini_memfrob generate" 
-}
-mini_fgetpos(){ 
-  echo "#define mini_fgetpos generate" 
-}
-mini_fileno(){ 
-  echo "#define mini_fileno generate" 
-}
-mini_dup3(){ 
-  echo "#define mini_dup3 generate" 
-}
-mini_strcmp(){ 
-  echo "#define mini_strcmp generate" 
-}
-mini_fclose(){ 
-  echo "#define mini_fclose generate" 
-}
-mini_close(){ 
-  echo "#define mini_close generate" 
-}
-mini_isprint(){ 
-  echo "#define mini_isprint generate" 
-}
-mini_snprintf(){ 
-  echo "#define mini_snprintf generate" 
-}
-mini_creat(){ 
-  echo "#define mini_creat generate" 
-}
-mini_stat(){ 
-  echo "#define mini_stat generate" 
-}
-mini_strncpy(){ 
-  echo "#define mini_strncpy generate" 
-}
-mini_def(){ 
-  echo "#define mini_def generate" 
-}
-mini_itohex(){ 
-  echo "#define mini_itohex generate" 
-}
-mini_sprintf(){ 
-  echo "#define mini_sprintf generate" 
-}
-mini_mprotect(){ 
-  echo "#define mini_mprotect generate" 
-}
-mini_getcwd(){ 
-  echo "#define mini_getcwd generate" 
-}
-mini_strerror(){ 
-  echo "#define mini_strerror generate" 
-}
-mini_rand(){ 
-  echo "#define mini_rand generate" 
-}
-mini_ftruncate(){ 
-  echo "#define mini_ftruncate generate" 
-}
-mini_dtodec(){ 
-  echo "#define mini_dtodec generate" 
-}
-mini_unlink(){ 
-  echo "#define mini_unlink generate" 
-}
-mini_write(){ 
-  echo "#define mini_write generate" 
-}
-mini__itohex(){ 
-  echo "#define mini__itohex generate" 
-}
-mini_getenv(){ 
-  echo "#define mini_getenv generate" 
-}
-mini_dup2(){ 
-  echo "#define mini_dup2 generate" 
+mini_strlen(){ 
+  echo "#define mini_strlen generate" 
 }
 mini_getpid(){ 
   echo "#define mini_getpid generate" 
 }
-mini_fsetpos(){ 
-  echo "#define mini_fsetpos generate" 
-}
-mini_fstat(){ 
-  echo "#define mini_fstat generate" 
-}
-mini_free(){ 
-  echo "#define mini_free generate" 
-}
-mini_read(){ 
-  echo "#define mini_read generate" 
-}
-mini_printf(){ 
-  echo "#define mini_printf generate" 
+mini_strncpy(){ 
+  echo "#define mini_strncpy generate" 
 }
 mini_memcmp(){ 
   echo "#define mini_memcmp generate" 
 }
-mini_fprintf(){ 
-  echo "#define mini_fprintf generate" 
-}
-mini_puts(){ 
-  echo "#define mini_puts generate" 
-}
-mini_dup(){ 
-  echo "#define mini_dup generate" 
-}
-mini_feof(){ 
-  echo "#define mini_feof generate" 
-}
-mini_fputc(){ 
-  echo "#define mini_fputc generate" 
-}
-mini_rename(){ 
-  echo "#define mini_rename generate" 
-}
-mini_ftell(){ 
-  echo "#define mini_ftell generate" 
+mini_dprintf(){ 
+  echo "#define mini_dprintf generate" 
 }
 mini_fopen(){ 
   echo "#define mini_fopen generate" 
 }
-mini_srand(){ 
-  echo "#define mini_srand generate" 
+mini_creat(){ 
+  echo "#define mini_creat generate" 
 }
-mini_time(){ 
-  echo "#define mini_time generate" 
+mini_puts(){ 
+  echo "#define mini_puts generate" 
 }
-mini_open(){ 
-  echo "#define mini_open generate" 
-}
-mini_itodec(){ 
-  echo "#define mini_itodec generate" 
-}
-mini__itobin(){ 
-  echo "#define mini__itobin generate" 
-}
-mini_tcgetattr(){ 
-  echo "#define mini_tcgetattr generate" 
-}
-mini_memcpy(){ 
-  echo "#define mini_memcpy generate" 
-}
-mini_memset(){ 
-  echo "#define mini_memset generate" 
-}
-mini_strlen(){ 
-  echo "#define mini_strlen generate" 
-}
-mini_vsnprintf(){ 
-  echo "#define mini_vsnprintf generate" 
-}
-mini_putchar(){ 
-  echo "#define mini_putchar generate" 
-}
-mini_printl(){ 
-  echo "#define mini_printl generate" 
-}
-mini_gettimeofday(){ 
-  echo "#define mini_gettimeofday generate" 
-}
-mini_ioctl(){ 
-  echo "#define mini_ioctl generate" 
-}
-mini_rewind(){ 
-  echo "#define mini_rewind generate" 
-}
-mini_strcpy(){ 
-  echo "#define mini_strcpy generate" 
-}
-mini_dprintf(){ 
-  echo "#define mini_dprintf generate" 
-}
-mini_strcat(){ 
-  echo "#define mini_strcat generate" 
-}
-mini_atoi(){ 
-  echo "#define mini_atoi generate" 
-}
-mini_lseek(){ 
-  echo "#define mini_lseek generate" 
-}
-mini_fseek(){ 
-  echo "#define mini_fseek generate" 
-}
-mini_fsync(){ 
-  echo "#define mini_fsync generate" 
-}
-mini_fwrite(){ 
-  echo "#define mini_fwrite generate" 
-}
-mini_fread(){ 
-  echo "#define mini_fread generate" 
-}
-mini_tcsetattr(){ 
-  echo "#define mini_tcsetattr generate" 
-}
-mini_fputs(){ 
-  echo "#define mini_fputs generate" 
+mini_unlink(){ 
+  echo "#define mini_unlink generate" 
 }
 mini_isspace(){ 
   echo "#define mini_isspace generate" 
 }
-mini_malloc(){ 
-  echo "#define mini_malloc generate" 
+mini_memfrob(){ 
+  echo "#define mini_memfrob generate" 
+}
+mini_putchar(){ 
+  echo "#define mini_putchar generate" 
 }
 mini_uitodec(){ 
   echo "#define mini_uitodec generate" 
 }
+mini_def(){ 
+  echo "#define mini_def generate" 
+}
+mini_fgetpos(){ 
+  echo "#define mini_fgetpos generate" 
+}
+mini_read(){ 
+  echo "#define mini_read generate" 
+}
+mini_rand(){ 
+  echo "#define mini_rand generate" 
+}
+mini_fileno(){ 
+  echo "#define mini_fileno generate" 
+}
+mini_itohex(){ 
+  echo "#define mini_itohex generate" 
+}
+mini_tcsetattr(){ 
+  echo "#define mini_tcsetattr generate" 
+}
+mini_itoHEX(){ 
+  echo "#define mini_itoHEX generate" 
+}
+mini_strcat(){ 
+  echo "#define mini_strcat generate" 
+}
 mini_select(){ 
   echo "#define mini_select generate" 
+}
+mini_dup(){ 
+  echo "#define mini_dup generate" 
+}
+mini_ftell(){ 
+  echo "#define mini_ftell generate" 
 }
 mini_print(){ 
   echo "#define mini_print generate" 
 }
+mini_strcpy(){ 
+  echo "#define mini_strcpy generate" 
+}
+mini_time(){ 
+  echo "#define mini_time generate" 
+}
+mini_fsync(){ 
+  echo "#define mini_fsync generate" 
+}
+mini_printl(){ 
+  echo "#define mini_printl generate" 
+}
+mini_fseek(){ 
+  echo "#define mini_fseek generate" 
+}
+mini_fwrite(){ 
+  echo "#define mini_fwrite generate" 
+}
+mini_getcwd(){ 
+  echo "#define mini_getcwd generate" 
+}
+mini_tcgetattr(){ 
+  echo "#define mini_tcgetattr generate" 
+}
+mini_close(){ 
+  echo "#define mini_close generate" 
+}
+mini_fclose(){ 
+  echo "#define mini_fclose generate" 
+}
+mini_sprintf(){ 
+  echo "#define mini_sprintf generate" 
+}
+mini_rename(){ 
+  echo "#define mini_rename generate" 
+}
+mini_strcmp(){ 
+  echo "#define mini_strcmp generate" 
+}
+mini_vsnprintf(){ 
+  echo "#define mini_vsnprintf generate" 
+}
+mini_itodec(){ 
+  echo "#define mini_itodec generate" 
+}
+mini_memset(){ 
+  echo "#define mini_memset generate" 
+}
+mini_malloc(){ 
+  echo "#define mini_malloc generate" 
+}
+mini_rewind(){ 
+  echo "#define mini_rewind generate" 
+}
+mini__itobin(){ 
+  echo "#define mini__itobin generate" 
+}
+mini_atoi(){ 
+  echo "#define mini_atoi generate" 
+}
+mini_fputc(){ 
+  echo "#define mini_fputc generate" 
+}
+mini_prints(){ 
+  echo "#define mini_prints generate" 
+}
+mini_fputs(){ 
+  echo "#define mini_fputs generate" 
+}
+mini_lseek(){ 
+  echo "#define mini_lseek generate" 
+}
+mini_fstat(){ 
+  echo "#define mini_fstat generate" 
+}
+mini_ftruncate(){ 
+  echo "#define mini_ftruncate generate" 
+}
 mini_strncmp(){ 
   echo "#define mini_strncmp generate" 
 }
-mini_itoHEX(){ 
-  echo "#define mini_itoHEX generate" 
+mini_getenv(){ 
+  echo "#define mini_getenv generate" 
+}
+mini_write(){ 
+  echo "#define mini_write generate" 
+}
+mini_fsetpos(){ 
+  echo "#define mini_fsetpos generate" 
+}
+mini_dtodec(){ 
+  echo "#define mini_dtodec generate" 
+}
+mini_memcpy(){ 
+  echo "#define mini_memcpy generate" 
+}
+mini_fread(){ 
+  echo "#define mini_fread generate" 
+}
+mini_dup3(){ 
+  echo "#define mini_dup3 generate" 
+}
+mini_mprotect(){ 
+  echo "#define mini_mprotect generate" 
+}
+mini_free(){ 
+  echo "#define mini_free generate" 
+}
+mini_open(){ 
+  echo "#define mini_open generate" 
+}
+mini_srand(){ 
+  echo "#define mini_srand generate" 
+}
+mini_snprintf(){ 
+  echo "#define mini_snprintf generate" 
+}
+mini_gettimeofday(){ 
+  echo "#define mini_gettimeofday generate" 
+}
+mini_isprint(){ 
+  echo "#define mini_isprint generate" 
+}
+mini_strerror(){ 
+  echo "#define mini_strerror generate" 
+}
+mini_feof(){ 
+  echo "#define mini_feof generate" 
+}
+mini_dup2(){ 
+  echo "#define mini_dup2 generate" 
+}
+mini_stat(){ 
+  echo "#define mini_stat generate" 
+}
+mini_printf(){ 
+  echo "#define mini_printf generate" 
+}
+mini_ioctl(){ 
+  echo "#define mini_ioctl generate" 
+}
+mini_fprintf(){ 
+  echo "#define mini_fprintf generate" 
+}
+mini__itohex(){ 
+  echo "#define mini__itohex generate" 
 }
 # --- define_functions-end: generate --- #
 
@@ -817,80 +852,81 @@ genconfigmacros_h='
 // when make header ist invoked
 
 // --- define_macros-start: generate --- //
-#define memfrob(...) _M_MLIB_memfrob_M_()
-#define fgetpos(...) _M_MLIB_fgetpos_M_()
-#define fileno(...) _M_MLIB_fileno_M_()
-#define dup3(...) _M_MLIB_dup3_M_()
-#define strcmp(...) _M_MLIB_strcmp_M_()
-#define fclose(...) _M_MLIB_fclose_M_()
-#define close(...) _M_MLIB_close_M_()
-#define isprint(...) _M_MLIB_isprint_M_()
-#define snprintf(...) _M_MLIB_snprintf_M_()
-#define creat(...) _M_MLIB_creat_M_()
-#define stat(...) _M_MLIB_stat_M_()
-#define strncpy(...) _M_MLIB_strncpy_M_()
-#define def(...) _M_MLIB_def_M_()
-#define itohex(...) _M_MLIB_itohex_M_()
-#define sprintf(...) _M_MLIB_sprintf_M_()
-#define mprotect(...) _M_MLIB_mprotect_M_()
-#define getcwd(...) _M_MLIB_getcwd_M_()
-#define strerror(...) _M_MLIB_strerror_M_()
-#define rand(...) _M_MLIB_rand_M_()
-#define ftruncate(...) _M_MLIB_ftruncate_M_()
-#define dtodec(...) _M_MLIB_dtodec_M_()
-#define unlink(...) _M_MLIB_unlink_M_()
-#define write(...) _M_MLIB_write_M_()
-#define _itohex(...) _M_MLIB__itohex_M_()
-#define getenv(...) _M_MLIB_getenv_M_()
-#define dup2(...) _M_MLIB_dup2_M_()
-#define getpid(...) _M_MLIB_getpid_M_()
-#define fsetpos(...) _M_MLIB_fsetpos_M_()
-#define fstat(...) _M_MLIB_fstat_M_()
-#define free(...) _M_MLIB_free_M_()
-#define read(...) _M_MLIB_read_M_()
-#define printf(...) _M_MLIB_printf_M_()
-#define memcmp(...) _M_MLIB_memcmp_M_()
-#define fprintf(...) _M_MLIB_fprintf_M_()
-#define puts(...) _M_MLIB_puts_M_()
-#define dup(...) _M_MLIB_dup_M_()
-#define feof(...) _M_MLIB_feof_M_()
-#define fputc(...) _M_MLIB_fputc_M_()
-#define rename(...) _M_MLIB_rename_M_()
-#define ftell(...) _M_MLIB_ftell_M_()
-#define fopen(...) _M_MLIB_fopen_M_()
-#define srand(...) _M_MLIB_srand_M_()
-#define time(...) _M_MLIB_time_M_()
-#define open(...) _M_MLIB_open_M_()
-#define itodec(...) _M_MLIB_itodec_M_()
-#define _itobin(...) _M_MLIB__itobin_M_()
-#define tcgetattr(...) _M_MLIB_tcgetattr_M_()
-#define memcpy(...) _M_MLIB_memcpy_M_()
-#define memset(...) _M_MLIB_memset_M_()
-#define strlen(...) _M_MLIB_strlen_M_()
-#define vsnprintf(...) _M_MLIB_vsnprintf_M_()
-#define putchar(...) _M_MLIB_putchar_M_()
-#define printl(...) _M_MLIB_printl_M_()
-#define gettimeofday(...) _M_MLIB_gettimeofday_M_()
-#define ioctl(...) _M_MLIB_ioctl_M_()
-#define rewind(...) _M_MLIB_rewind_M_()
-#define strcpy(...) _M_MLIB_strcpy_M_()
-#define dprintf(...) _M_MLIB_dprintf_M_()
-#define strcat(...) _M_MLIB_strcat_M_()
-#define atoi(...) _M_MLIB_atoi_M_()
-#define lseek(...) _M_MLIB_lseek_M_()
-#define fseek(...) _M_MLIB_fseek_M_()
-#define fsync(...) _M_MLIB_fsync_M_()
-#define fwrite(...) _M_MLIB_fwrite_M_()
-#define fread(...) _M_MLIB_fread_M_()
-#define tcsetattr(...) _M_MLIB_tcsetattr_M_()
-#define fputs(...) _M_MLIB_fputs_M_()
-#define isspace(...) _M_MLIB_isspace_M_()
-#define malloc(...) _M_MLIB_malloc_M_()
-#define uitodec(...) _M_MLIB_uitodec_M_()
-#define select(...) _M_MLIB_select_M_()
-#define print(...) _M_MLIB_print_M_()
-#define strncmp(...) _M_MLIB_strncmp_M_()
-#define itoHEX(...) _M_MLIB_itoHEX_M_()
+#define strlen(...) _M_MLIB_strlen_M_(__VA_ARGS__)
+#define getpid(...) _M_MLIB_getpid_M_(__VA_ARGS__)
+#define strncpy(...) _M_MLIB_strncpy_M_(__VA_ARGS__)
+#define memcmp(...) _M_MLIB_memcmp_M_(__VA_ARGS__)
+#define dprintf(...) _M_MLIB_dprintf_M_(__VA_ARGS__)
+#define fopen(...) _M_MLIB_fopen_M_(__VA_ARGS__)
+#define creat(...) _M_MLIB_creat_M_(__VA_ARGS__)
+#define puts(...) _M_MLIB_puts_M_(__VA_ARGS__)
+#define unlink(...) _M_MLIB_unlink_M_(__VA_ARGS__)
+#define isspace(...) _M_MLIB_isspace_M_(__VA_ARGS__)
+#define memfrob(...) _M_MLIB_memfrob_M_(__VA_ARGS__)
+#define putchar(...) _M_MLIB_putchar_M_(__VA_ARGS__)
+#define uitodec(...) _M_MLIB_uitodec_M_(__VA_ARGS__)
+#define def(...) _M_MLIB_def_M_(__VA_ARGS__)
+#define fgetpos(...) _M_MLIB_fgetpos_M_(__VA_ARGS__)
+#define read(...) _M_MLIB_read_M_(__VA_ARGS__)
+#define rand(...) _M_MLIB_rand_M_(__VA_ARGS__)
+#define fileno(...) _M_MLIB_fileno_M_(__VA_ARGS__)
+#define itohex(...) _M_MLIB_itohex_M_(__VA_ARGS__)
+#define tcsetattr(...) _M_MLIB_tcsetattr_M_(__VA_ARGS__)
+#define itoHEX(...) _M_MLIB_itoHEX_M_(__VA_ARGS__)
+#define strcat(...) _M_MLIB_strcat_M_(__VA_ARGS__)
+#define select(...) _M_MLIB_select_M_(__VA_ARGS__)
+#define dup(...) _M_MLIB_dup_M_(__VA_ARGS__)
+#define ftell(...) _M_MLIB_ftell_M_(__VA_ARGS__)
+#define print(...) _M_MLIB_print_M_(__VA_ARGS__)
+#define strcpy(...) _M_MLIB_strcpy_M_(__VA_ARGS__)
+#define time(...) _M_MLIB_time_M_(__VA_ARGS__)
+#define fsync(...) _M_MLIB_fsync_M_(__VA_ARGS__)
+#define printl(...) _M_MLIB_printl_M_(__VA_ARGS__)
+#define fseek(...) _M_MLIB_fseek_M_(__VA_ARGS__)
+#define fwrite(...) _M_MLIB_fwrite_M_(__VA_ARGS__)
+#define getcwd(...) _M_MLIB_getcwd_M_(__VA_ARGS__)
+#define tcgetattr(...) _M_MLIB_tcgetattr_M_(__VA_ARGS__)
+#define close(...) _M_MLIB_close_M_(__VA_ARGS__)
+#define fclose(...) _M_MLIB_fclose_M_(__VA_ARGS__)
+#define sprintf(...) _M_MLIB_sprintf_M_(__VA_ARGS__)
+#define rename(...) _M_MLIB_rename_M_(__VA_ARGS__)
+#define strcmp(...) _M_MLIB_strcmp_M_(__VA_ARGS__)
+#define vsnprintf(...) _M_MLIB_vsnprintf_M_(__VA_ARGS__)
+#define itodec(...) _M_MLIB_itodec_M_(__VA_ARGS__)
+#define memset(...) _M_MLIB_memset_M_(__VA_ARGS__)
+#define malloc(...) _M_MLIB_malloc_M_(__VA_ARGS__)
+#define rewind(...) _M_MLIB_rewind_M_(__VA_ARGS__)
+#define _itobin(...) _M_MLIB__itobin_M_(__VA_ARGS__)
+#define atoi(...) _M_MLIB_atoi_M_(__VA_ARGS__)
+#define fputc(...) _M_MLIB_fputc_M_(__VA_ARGS__)
+#define prints(...) _M_MLIB_prints_M_(__VA_ARGS__)
+#define fputs(...) _M_MLIB_fputs_M_(__VA_ARGS__)
+#define lseek(...) _M_MLIB_lseek_M_(__VA_ARGS__)
+#define fstat(...) _M_MLIB_fstat_M_(__VA_ARGS__)
+#define ftruncate(...) _M_MLIB_ftruncate_M_(__VA_ARGS__)
+#define strncmp(...) _M_MLIB_strncmp_M_(__VA_ARGS__)
+#define getenv(...) _M_MLIB_getenv_M_(__VA_ARGS__)
+#define write(...) _M_MLIB_write_M_(__VA_ARGS__)
+#define fsetpos(...) _M_MLIB_fsetpos_M_(__VA_ARGS__)
+#define dtodec(...) _M_MLIB_dtodec_M_(__VA_ARGS__)
+#define memcpy(...) _M_MLIB_memcpy_M_(__VA_ARGS__)
+#define fread(...) _M_MLIB_fread_M_(__VA_ARGS__)
+#define dup3(...) _M_MLIB_dup3_M_(__VA_ARGS__)
+#define mprotect(...) _M_MLIB_mprotect_M_(__VA_ARGS__)
+#define free(...) _M_MLIB_free_M_(__VA_ARGS__)
+#define open(...) _M_MLIB_open_M_(__VA_ARGS__)
+#define srand(...) _M_MLIB_srand_M_(__VA_ARGS__)
+#define snprintf(...) _M_MLIB_snprintf_M_(__VA_ARGS__)
+#define gettimeofday(...) _M_MLIB_gettimeofday_M_(__VA_ARGS__)
+#define isprint(...) _M_MLIB_isprint_M_(__VA_ARGS__)
+#define strerror(...) _M_MLIB_strerror_M_(__VA_ARGS__)
+#define feof(...) _M_MLIB_feof_M_(__VA_ARGS__)
+#define dup2(...) _M_MLIB_dup2_M_(__VA_ARGS__)
+#define stat(...) _M_MLIB_stat_M_(__VA_ARGS__)
+#define printf(...) _M_MLIB_printf_M_(__VA_ARGS__)
+#define ioctl(...) _M_MLIB_ioctl_M_(__VA_ARGS__)
+#define fprintf(...) _M_MLIB_fprintf_M_(__VA_ARGS__)
+#define _itohex(...) _M_MLIB__itohex_M_(__VA_ARGS__)
 // --- define_macros-end: generate --- //
 // --- content-genconf-macros-end: TMPL ---
 '
@@ -906,7 +942,7 @@ headerguards_h='
 #define included_declarations_h
 #define included_fcntl_h
 #define included_ioctl_h
-#define included_miniextras_h
+#define included_miniaddons_h
 #define included_stdio_h
 #define included_stdlib_h
 #define included_string_h
